export const SESSION_LOGIN = 'SESSION_LOGIN';
export const SESSION_LOGOUT = 'SESSION_LOGOUT';
export const SESSION_REQUESTING_USER = 'SESSION_REQUESTING_USER';

export const PLAYER_PLAY = 'PLAYER_PLAY';
export const PLAYER_PAUSE = 'PLAYER_PAUSE';
export const PLAYER_SET_TRACK = 'PLAYER_SET_TRACK';
export const PLAYER_INCREMENT_POSITION = 'PLAYER_INCREMENT_POSITION';
export const PLAYER_SET_INTERVAL_ID = 'PLAYER_SET_INTERVAL_ID';